### ISSUE TITLE
TODO: Data Review Update

### ISSUE THREAD

**Issue by sebastiandig** [sebastiandig/obis_zooplankton_setup#3]
Hi @7yl4r,

Take a look over this and we should talk about getting this moved along.  

Here is a summary of the [Data Review](https://github.com/ioos/bio_data_guide/issues/136) as suggested by Abbey.
I have updated examples of data [here](https://github.com/USF-IMARS/zoo-taxonomy-to-darwin-core/tree/master/data).

Summary:
- [ ] There should be no overlap between fields in the event table and fields in the occurrence table
- [ ] label on vials that are stored
- [x] drop `basisOfRecord`, `recordedBy`, and `recordedByID` from *event*, only for *occurence*
  
- [ ] drop `parentEventID`
    * unless you will have information that will only be included at the parent 
      level and not repeated in the child events
      
- [ ] need `institutionCode` when doing *PreservedSpecimen*, I guess
- [ ] needs a `collectionCode` since it's preserved?

- [ ] `datasetName` include *zoo*, *location*, *mesh*?
   * something unqiue to other FL MBON

- [x] suggest dropping `informationWithheld`

- [x] drop `eventDateTime` and `eventTime` 
- [x] rename `eventDateTime` to `eventDate`
- [ ]  `eventDate` is in UTC, maybe I need to add +0000?

- [ ] yes, the naming is an issue because some taxa can only be identified to a certain level that may be shared between two or more
  - ex. `Veliger Larvae` can only be identified to `Bivalvia` and `Bivalve larvae` is also `Bivalvia`, so when creating `occurrenceID`, they would be the same.

    - [ ] I need to go back to the drawing board?

- [x] drop `taxonID`

- [ ] drop `individualCount` in *occurence*, but keep in *MoF*?

- [ ] Any *measurements or facts* that are about the occurrences need to have `occurrenceID` added. 
    - Abby: I think it's only `"Abundance"` and `"Count"` that would need to have `occurrenceID` added but if there are any others that relate specifically to the occurrence then you'll need to add it there too.

- [ ] drop `measurementUnitID` and keep in *MoF*

- [x] drop `establishmentMeans`

- [x] drop `datasetID`, `eventDate` and any other fields that are already in the *event* core.

- [x] `georeferenceVerificationStatus` instead of `georeferenceVerificationStatusProperty`

- [x] `datasetID` from the *eMoF* table

**Comment by sebastiandig** [comment]
edited with @7yl4r

**Comment by sebastiandig** [comment]
add update
